config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users, :sessions

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get 'sign-in' => 'authentication#new', as: :signin
  post 'sign-in' => 'authentication#create'
  get 'sign-out' => 'authentication#destroy', as: :signout

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
  get '/logout', :to => 'sessions#destroy'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessor :provider, :uid, :user_id, :user
  belongs_to :user
  validates :provider, :uid, :presence => true

  # def self.find_or_create(auth_hash)
  # unless auth = find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
  #   user = User.create :first_name => auth_hash["info"]["first_name"], :email => auth_hash["info"]["email"]
  #   auth = create :user => user, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
  # end
  #
  # auth
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password

  # def add_provider(auth_hash)
  # # Check if the provider already exists, so we don't add it twice
  # unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
  #   Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user
  
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @sign_in_error = "Email/password combination is invalid"
      render :new
    end
  end
  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_registration, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation))
    if @user.save
      session[:user_id]=@user.id
      redirect_to root_path
    else
      render :new
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    auth_hash = request.env['omniauth.auth']

    @authorization = Authorization.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    if @authorization
      render :text => "Welcome back #{@authorization.user.name}! You have already signed up."
    else
      user = User.new :first_name => auth_hash["info"]["first_name"], :email => auth_hash["info"]["email"]
      user.authorizations.build :provider => auth_hash["provider"], :uid => auth_hash["uid"]
      user.save

      redirect_to root_path
    end
  end

  def failure

  end

  def index
    @foursquare = []
    response = RestClient.get('https://api.foursquare.com/v2/users/self/checkins?oauth_token=2TIM1DJ1POSQC2T3SF01YA2XX4GBPDFWT5YRTFZA40PYBNJ4&v=20150205')
    @checkins_hash = JSON.parse(response.body)["response"]["checkins"]["items"]
    @checkins_hash.each do |c|
      puts c["venue"]["name"]
    end
  end

  def destroy
    session[:user_id] = nil
    render :text => "You've logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    @foursquare = []
    response = RestClient.get('https://api.foursquare.com/v2/users/self/checkins?oauth_token=2TIM1DJ1POSQC2T3SF01YA2XX4GBPDFWT5YRTFZA40PYBNJ4&v=20150205')
    @checkins_hash = JSON.parse(response.body)["response"]["checkins"]["items"]
    @checkins_hash.each do |c|
      puts c["venue"]["name"]
    end
      # puts url
      # begin
      #   data = RestClient.get(url)
      #   res = JSON.parse(data.body)
      #   res.each do |foursquare|
      #     @foursquare << foursquare["items"]

        # end
      # rescue => e
      #   puts e.response
      # end

    # end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render:new
    end
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render:edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
      redirect_to users_path, notice: 'User was successfully deleted.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password_digest
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authentication/new.html.erb
<div class = "container-fluid">
<h1>Sign In</h1>


<%= form_tag signin_path do |f| %>

  <% if @sign_in_error %>
    <p>
      <%= @sign_in_error %>
    </p>
  <% end %>
  <div class="ui form segment">
    <div class="fields">
      <div class="field">
        <%= label_tag :email %>
      </div>
      <div class="six wide field">
        <%= email_field_tag :email %>
      </div>
      <div class="field">
        <%= label_tag :password %>
      </div>
      <div class="six wide field">
        <%= password_field_tag :password %>
      </div>
      <div>
        <%= submit_tag "Sign In"%>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoveShtuff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "container-fluid">
    <nav class="navbar-header navbar-right">

    <% if current_user %>
      <%= link_to "Sign Out", signout_path %>
    <% else %>
      <%= link_to "Sign Up", signup_path %>|
      <%= link_to "Sign In", signin_path %>
    <% end %>

    </nav>


  </div>
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>LoveShtuff</h1>


<div class="ui breadcrumb">
  <div class="active section">Present</a>
  <div class="divider"> / </div>
  <a class="section"><%= link_to "Past", sessions_path %></a>
  <div class="divider"> / </div>
  <a class="section">Future</div>
</div>

<div class="ui blue basic button"><%= link_to "Connect With Foursquare", "/auth/foursquare" %></div>